name: Greeting on variable day

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job_linux:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

  greeting_job_win:
    runs-on: windows-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$env:Greeting $env:First_Name. Today is $env:DAY_OF_WEEK!"
        env:
          First_Name: Mona
