name: the-workflow

on:
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io
  NPM_EMAIL: ${{ secrets.DIST_PLAT_DEPLOYER_USERNAME }}
  NPM_AUTH: ${{ secrets.DIST_PLAT_DEPLOYER_NPM_AUTH }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Registry
        run: echo "${{ secrets.GH_TOKEN_READER }}" | docker login "${GITHUB_REGISTRY}" -u none --password-stdin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install -g @vscode/vsce
      - run: npm install -g webpack
      - run : vsce package
    