name: the-workflow

on:
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io
  NPM_EMAIL: antoniovazquezaraujo@gmail.com
  NPM_AUTH: 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

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install -g @vscode/vsce
      - run: npm install -D webpack-cli
      - run : vsce package
    