name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: uno
        run: |
          echo "nombre='Antonio'" >> $env:GITHUB_ENV
      - name: dos
        run: |
          echo "Mi nombre es $Env:nombre "

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "Funciona esto?"
          echo "${{ env.action_state }}" # This will output 'yellow'          
          echo "Fin"
